# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'restock form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RestockForm(object):
    def setupUi(self, RestockForm):
        RestockForm.setObjectName("RestockForm")
        RestockForm.resize(640, 521)
        self.CompanygroupBox = QGroupBox("Company Details")
        self.CompanygroupBox.setGeometry(QtCore.QRect(20, 30, 421, 121))
        self.CompanygroupBox.setObjectName("CompanygroupBox")
        self.companylabel = QtWidgets.QLabel(self.CompanygroupBox)
        self.companylabel.setGeometry(QtCore.QRect(20, 30, 71, 16))

        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.companylabel.setFont(font)
        self.companylabel.setObjectName("companylabel")
        self.companylabel.setText("Company : ")
        self.CompanyfontComboBox = QtWidgets.QFontComboBox(self.CompanygroupBox)
        self.CompanyfontComboBox.setGeometry(QtCore.QRect(100, 30, 231, 22))
        self.CompanyfontComboBox.setObjectName("CompanyfontComboBox")
        self.companylabel_2 = QtWidgets.QLabel(self.CompanygroupBox)
        self.companylabel_2.setGeometry(QtCore.QRect(20, 70, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.companylabel_2.setFont(font)
        self.companylabel_2.setObjectName("companylabel_2")
        self.companylabel_2.setText("Category : ")
        self.comboBox = QtWidgets.QComboBox(self.CompanygroupBox)
        self.comboBox.setGeometry(QtCore.QRect(100, 70, 151, 22))
        self.comboBox.setObjectName("comboBox")
        self.companylabel_3 = QtWidgets.QLabel(RestockForm)
        self.companylabel_3.setGeometry(QtCore.QRect(460, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.companylabel_3.setFont(font)
        self.companylabel_3.setObjectName("companylabel_3")
        self.companylabel_3.setText("Order ID :")
        self.spinBox = QtWidgets.QSpinBox(RestockForm)
        self.spinBox.setGeometry(QtCore.QRect(540, 40, 42, 22))
        self.spinBox.setMaximum(9999)
        self.spinBox.setObjectName("spinBox")
        self.companylabel_4 = QtWidgets.QLabel(RestockForm)
        self.companylabel_4.setGeometry(QtCore.QRect(460, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.companylabel_4.setFont(font)
        self.companylabel_4.setObjectName("companylabel_4")
        self.companylabel_4.setText("Date :")
        self.dateEdit = QtWidgets.QDateEdit(RestockForm)
        self.dateEdit.setGeometry(QtCore.QRect(510, 90, 110, 22))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2018, 12, 11))
        self.dateEdit.setObjectName("dateEdit")
        self.tableWidget = QtWidgets.QTableWidget(RestockForm)
        self.tableWidget.setGeometry(QtCore.QRect(20, 150, 412, 57))
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.HLine)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText("Cash")
        self.tableWidget.setHorizontalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText("C.O.D")
        self.tableWidget.setHorizontalHeaderItem(1, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText("Paid Out")
        self.tableWidget.setHorizontalHeaderItem(2, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText("Shipped VIA")
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.orderrecomview = QtWidgets.QTableWidget(RestockForm)
        self.orderrecomview.setGeometry(QtCore.QRect(20, 210, 611, 211))
        self.orderrecomview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.orderrecomview.setDragEnabled(True)
        self.orderrecomview.setRowCount(10)
        self.orderrecomview.setObjectName("orderrecomview")
        self.orderrecomview.setColumnCount(6)

        item = QtWidgets.QTableWidgetItem()
        item.setText("Qty")
        self.orderrecomview.setHorizontalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText("Stock No.")
        self.orderrecomview.setHorizontalHeaderItem(1, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText("Name")
        self.orderrecomview.setHorizontalHeaderItem(2, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText("Brand")
        self.orderrecomview.setHorizontalHeaderItem(3, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText("Unit Price")
        self.orderrecomview.setHorizontalHeaderItem(4, item)

        item = QtWidgets.QTableWidgetItem()
        item.setText("Total Price")
        self.orderrecomview.setHorizontalHeaderItem(5, item)

        self.orderrecomview.verticalHeader().setVisible(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(RestockForm)
        self.buttonBox.setGeometry(QtCore.QRect(460, 460, 161, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

    def retranslateUi(self, RestockForm):
        _translate = QtCore.QCoreApplication.translate
        RestockForm.setWindowTitle(_translate("RestockForm", "Form"))
        self.CompanygroupBox.setTitle(_translate("RestockForm", "Company Details"))
        self.companylabel.setText(_translate("RestockForm", "Company : "))
        self.companylabel_2.setText(_translate("RestockForm", "Category : "))
        self.companylabel_3.setText(_translate("RestockForm", "Order ID :"))
        self.companylabel_4.setText(_translate("RestockForm", "Date :"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("RestockForm", "Cash"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("RestockForm", "C.O.D"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("RestockForm", "Paid Out"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("RestockForm", "Shipped VIA"))
        item = self.orderrecomview.horizontalHeaderItem(0)
        item.setText(_translate("RestockForm", "Qty"))
        item = self.orderrecomview.horizontalHeaderItem(1)
        item.setText(_translate("RestockForm", "Stock No."))
        item = self.orderrecomview.horizontalHeaderItem(2)
        item.setText(_translate("RestockForm", "Name"))
        item = self.orderrecomview.horizontalHeaderItem(3)
        item.setText(_translate("RestockForm", "Brand"))
        item = self.orderrecomview.horizontalHeaderItem(4)
        item.setText(_translate("RestockForm", "Unit Price"))
        item = self.orderrecomview.horizontalHeaderItem(5)
        item.setText(_translate("RestockForm", "Total Price"))

